import random
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification, Trainer, TrainingArguments
from transformers import DataCollatorWithPadding

math_questions = [
    "What is 23 + 57?", "Calculate 10 * 15", "What is 200 divided by 4?",
    "Find the remainder when 45 is divided by 6", "What is the square root of 144?",
    "Solve for x: 3x - 7 = 8", "Factorize x^2 - 5x + 6", "Expand (x + 3)(x - 2)",
    "Find the value of x in 2x^2 + 3x - 5 = 0", "Simplify: (2x + 3) / (x + 1)",
    "Differentiate x^3 + 5x - 2", "Find the integral of sin(x) dx",
    "What is the limit of (x^2 - 1) / (x - 1) as x approaches 1?",
    "Compute the second derivative of e^x", "Find the Taylor series of cos(x) at x=0",
    "Find the determinant of this matrix: [[2,3],[4,5]]",
    "Compute the eigenvalues of [[1,2],[2,1]]", "What is the rank of this matrix?",
    "Find the inverse of [[1,2],[3,4]]", "Solve this system of equations: x + y = 5, x - y = 3",
    "What is the probability of flipping a fair coin and getting heads?",
    "Calculate the standard deviation of these numbers: [4, 8, 6, 10, 12]",
    "Find the mean of [5, 10, 15, 20]", "What is the variance of [2, 4, 6, 8, 10]?",
    "Explain Bayes' Theorem",
    "Find the area of a triangle with base 5 and height 12",
    "Calculate the circumference of a circle with radius 7",
    "What is the Pythagorean theorem?", "Find sin(30 degrees)",
    "Convert 45 degrees to radians",
    "Find the next number in the Fibonacci sequence: 1, 1, 2, 3, 5, 8, ...",
    "What is the logical negation of (p ∧ q)?",
    "Explain De Morgan's Laws", "Convert binary 1010 to decimal",
    "How many ways can you arrange the letters in 'MATH'?",
    "Using F = ma, find the force if m=10kg and a=5m/s^2",
    "Find the kinetic energy of an object with mass 3kg moving at 4m/s",
    "Calculate the work done when a force of 20N moves an object 5m",
    "What is the gravitational potential energy of a 10kg object at 5m height?",
    "Compute the velocity of an object dropped from a height of 10m",
    "What is 157 + 293?",
    "How do you multiply two fractions?",
    "What is 18 divided by 3?",
    "Find the greatest common divisor of 24 and 36.",
    "What is the least common multiple of 6 and 9?",
    "What is 3 to the power of 4?",
    "What is the absolute value of -25?",
    "Round 9.876 to two decimal places.",
    "What is 12% of 250?",
    "What is the square root of 289?",
    "Solve for x: 5x + 2 = 17.",
    "Factorize the expression x^2 - 9.",
    "Expand the expression (x + 4)(x - 3).",
    "What is the value of x in 3x^2 - 2x - 8 = 0?",
    "What is the quadratic formula?",
    "Simplify the expression (2x + 4) / 2.",
    "What is the sum of the roots of x^2 - 7x + 12 = 0?",
    "What is the difference between a function and an equation?",
    "How do you graph a linear equation?",
    "What is an asymptote?",
    "Find the area of a triangle with base 10 and height 5.",
    "What is the perimeter of a rectangle with length 8 and width 6?",
    "Calculate the circumference of a circle with a radius of 7.",
    "Find the volume of a cube with side length 4.",
    "What is the Pythagorean theorem?",
    "What is the sum of the interior angles of a pentagon?",
    "What is the measure of each exterior angle in a regular octagon?",
    "What is the distance between points (3,4) and (7,1)?",
    "What is the equation of a circle centered at (0,0) with a radius of 5?",
    "Define congruent triangles.",
    "Differentiate the function f(x) = x^3 + 2x.",
    "Find the integral of sin(x) dx.",
    "What is the limit of (x^2 - 1) / (x - 1) as x approaches 1?",
    "Compute the derivative of e^x.",
    "Find the second derivative of cos(x).",
    "What is the Fundamental Theorem of Calculus?",
    "Evaluate the definite integral from 0 to 2 of (x^2 dx).",
    "What is the Taylor series of e^x?",
    "Find the critical points of the function f(x) = x^4 - 4x^2 + 3.",
    "What is a partial derivative?",
    "Find the determinant of the matrix [[2,3],[4,5]].",
    "Compute the eigenvalues of [[1,2],[2,1]].",
    "What is the rank of a matrix?",
    "Find the inverse of the matrix [[1,2],[3,4]].",
    "Solve this system of equations: x + y = 5, x - y = 3.",
    "What is a dot product of two vectors?",
    "What is a cross product of two vectors?",
    "How do you diagonalize a matrix?",
    "What is an orthogonal matrix?",
    "What are linearly dependent vectors?",
    "What is the probability of rolling a 6 on a fair die?",
    "Find the mean of the numbers [4, 8, 6, 10, 12].",
    "What is the median of [5, 10, 15, 20, 25]?",
    "Define standard deviation.",
    "What is a normal distribution?",
    "What is the variance of [2, 4, 6, 8, 10]?",
    "Explain Bayes' Theorem.",
    "What is a p-value in statistics?",
    "Define correlation vs. causation.",
    "What is a confidence interval?",
    "Find the next term in the Fibonacci sequence: 1, 1, 2, 3, 5, ...",
    "How many ways can you arrange the letters in 'MATH'?",
    "What is a prime number?",
    "What is the binary representation of 45?",
    "Convert the hexadecimal number A3 to decimal.",
    "What is an algorithm?",
    "What is a logical AND operation?",
    "What is a set intersection?",
    "How do you prove a statement using mathematical induction?",
    "What is the difference between permutations and combinations?",
    "Using F = ma, find the force if m=10kg and a=5m/s^2.",
    "Find the kinetic energy of an object with mass 3kg moving at 4m/s.",
    "Calculate the work done when a force of 20N moves an object 5m.",
    "What is the gravitational potential energy of a 10kg object at 5m height?",
    "Compute the velocity of an object dropped from a height of 10m.",
    "What is Ohm’s Law?",
    "Find the period of a pendulum with a length of 2 meters.",
    "What is the speed of light?",
    "What is the formula for calculating pressure?",
    "How do you calculate torque?",
    "What is an irrational number?",
    "What is a transcendental number?",
    "What is the golden ratio?",
    "What is a fractal?",
    "Explain the Monty Hall problem.",
    "What is a Markov chain?",
    "What is the Collatz Conjecture?",
    "What is a differential equation?",
    "Define an exponential function.",
    "What is an imaginary number?",
]

non_math_questions = [
    "What is the latest movie trending?", "Tell me a funny joke",
    "Who won the last Olympic gold medal in swimming?",
    "What’s the weather forecast for tomorrow?", "Explain quantum computing",
    "How do I bake a chocolate cake?", "What are the best travel destinations in 2024?",
    "Tell me a story about a lost puppy", "Who wrote the book '1984'?",
    "How do I improve my memory?", "What are the health benefits of yoga?",
    "Give me tips for learning a new language", "What’s the history of the internet?",
    "What is the meaning of life?", "Who is the CEO of Tesla?",
    "Tell me about the history of ancient Egypt", "Explain how airplanes fly",
    "Give me the latest tech news", "How do I start a small business?",
    "What are the symptoms of the flu?", "Who is the president of the United States?",
    "Tell me about black holes", "How do I invest in stocks?",
    "What are some good books to read?", "Tell me a fun fact about space",
    "Who invented the telephone?", "How does photosynthesis work?",
    "What’s the best way to learn programming?", "What are the rules of chess?",
    "Tell me a riddle", "What are the benefits of meditation?",
    "Who was the first person to walk on the moon?", "Explain blockchain technology",
    "Who is the current president of the United States?",
    "What is the capital of Japan?",
    "How do I learn a new language efficiently?",
    "What are some good habits for productivity?",
    "Tell me a fun fact about space.",
    "What is the tallest mountain in the world?",
    "Who wrote the book 'To Kill a Mockingbird'?",
    "Why is the sky blue?",
    "How do airplanes stay in the air?",
    "What is the meaning of life?",
    "Explain how photosynthesis works.",
    "What is the theory of relativity?",
    "What are black holes?",
    "How does Wi-Fi work?",
    "What is quantum computing?",
    "How does a refrigerator keep food cold?",
    "What are the basic principles of electricity?",
    "How does a touchscreen work?",
    "What is artificial intelligence?",
    "What is the function of DNA?",
    "Who was Julius Caesar?",
    "What was the Cold War?",
    "What caused World War II?",
    "Who discovered America?",
    "When did the first humans land on the moon?",
    "What was the Renaissance?",
    "Who were the Vikings?",
    "What was the Great Depression?",
    "Who was the first emperor of China?",
    "Why did the Berlin Wall fall?",
    "Who won the last Academy Award for Best Picture?",
    "What are the top trending songs this year?",
    "Who is the highest-paid actor in Hollywood?",
    "What are some of the best TV shows of all time?",
    "What is the Harry Potter series about?",
    "What is the most popular video game right now?",
    "Who directed the movie 'Inception'?",
    "What are some upcoming Marvel movies?",
    "Who is the most famous YouTuber?",
    "What is the plot of 'Game of Thrones'?",
    "Who won the last FIFA World Cup?",
    "What are the rules of basketball?",
    "Who is the greatest tennis player of all time?",
    "How do you score points in American football?",
    "What is the difference between soccer and rugby?",
    "Who holds the world record for the 100-meter sprint?",
    "Which country has won the most Olympic medals?",
    "What is the history of the Super Bowl?",
    "Who is the most successful Formula 1 driver?",
    "How does the Tour de France work?",
    "What are some tips for losing weight?",
    "How does intermittent fasting work?",
    "What are the benefits of yoga?",
    "What is the healthiest diet?",
    "How much water should I drink every day?",
    "What are some exercises to build muscle?",
    "How do I improve my posture?",
    "What are the symptoms of dehydration?",
    "Why is sleep important for health?",
    "What are the benefits of meditation?",
    "What are the best places to visit in Europe?",
    "How do I prepare for a long flight?",
    "What are some must-visit landmarks in Paris?",
    "How can I travel on a budget?",
    "What are the safest countries to visit?",
    "How do I apply for a travel visa?",
    "What are the best beaches in the world?",
    "How do I avoid jet lag?",
    "What are the most beautiful national parks in the USA?",
    "How do I pack efficiently for a trip?",
    "How do I start my own business?",
    "What are the basics of investing?",
    "How does the stock market work?",
    "What is cryptocurrency?",
    "How do I create a budget?",
    "What are some passive income ideas?",
    "How do I build a strong credit score?",
    "What is the difference between a savings and checking account?",
    "How does inflation affect the economy?",
    "What are the best ways to save money?",
    "How do I become more confident?",
    "What are some effective time management techniques?",
    "How can I stay motivated?",
    "What are the benefits of journaling?",
    "How do I improve my communication skills?",
    "What are the best books for self-improvement?",
    "How do I develop emotional intelligence?",
    "What are some ways to reduce stress?",
    "How do I build better habits?",
    "What are some ways to increase creativity?",
    "Tell me a joke!",
    "What are some interesting conspiracy theories?",
    "What is the weirdest fact you know?",
    "What are some cool science experiments I can do at home?",
    "What is the best way to make a paper airplane?",
    "How do I solve a Rubik's Cube?",
    "What are some good riddles?",
    "If you could time travel, where would you go?",
    "What are some weird laws that still exist?",
    "Tell me a fun fact about animals.",
    "How do seasons change on Earth?",
    "What is the national animal of Canada?",
    "Who invented the lightbulb?",
    "What is the speed of light?",
    "How many continents are there?",
    "Why do birds migrate?",
    "What is the purpose of the United Nations?",
    "How do magnets work?",
    "What is the human body's largest organ?",
    "Why does metal rust?",
    "What is the difference between a virus and bacteria?",
    "How do 3D printers work?",
    "What is the function of a neuron?",
    "How does a microwave oven heat food?",
    "Why do helium balloons float?",
    "What is a supernova?",
    "How do submarines dive and resurface?",
    "What is the greenhouse effect?",
    "Why do our eyes adjust to darkness?",
    "What is the function of the ozone layer?",
    "Who was Cleopatra?",
    "What was the Industrial Revolution?",
    "Why did the Titanic sink?",
    "Who built the Great Wall of China?",
    "What was the Space Race?",
    "How did the printing press change the world?",
    "Who was the first human in space?",
    "What happened during the French Revolution?",
    "Who was Abraham Lincoln?",
    "What was the Manhattan Project?",
    "What is the longest-running TV show?",
    "What are some classic Disney movies?",
    "Who are the members of The Beatles?",
    "What is the Marvel Cinematic Universe?",
    "Who wrote the Lord of the Rings books?",
    "What are the different genres of music?",
    "What is the difference between anime and cartoons?",
    "Who are the main characters in Star Wars?",
    "What is the highest-grossing movie of all time?",
    "How does the Oscars voting system work?",
    "What is the offside rule in soccer?",
    "Who has won the most NBA championships?",
    "What is the history of the Olympic Games?",
    "How do you play cricket?",
    "What is the most popular sport in the world?",
    "What are the different types of martial arts?",
    "How is a baseball game structured?",
    "What is the difference between a marathon and a sprint?",
    "Who is the fastest swimmer in the world?",
    "How does a chess clock work?",
    "What are some good post-workout meals?",
    "How does caffeine affect the body?",
    "What is the difference between aerobic and anaerobic exercise?",
    "How do vaccines work?",
    "What are the benefits of drinking green tea?",
    "How does stress affect the immune system?",
    "What is mindfulness meditation?",
    "What are the effects of sugar on the body?",
    "Why do people get allergies?",
    "How does the body heal from a wound?",
    "What are some of the most dangerous places to visit?",
    "How do I get a passport?",
    "What are the best travel tips for solo travelers?",
    "How do time zones work?",
    "What is the best way to learn a new language while traveling?",
    "What are some good souvenirs to buy in Japan?",
    "What are the most eco-friendly travel destinations?",
    "How do I find cheap flights?",
    "What are the best travel insurance options?",
    "What is the best way to avoid tourist traps?",
    "What are some common investment mistakes?",
    "How do taxes work?",
    "What is the best way to negotiate a salary?",
    "How do I write a business plan?",
    "What are the benefits of a Roth IRA?",
    "How do credit cards work?",
    "What is the difference between a loan and a mortgage?",
    "How do I start an online business?",
    "What is compound interest?",
    "How do I build an emergency fund?",
    "What are the best strategies for setting goals?",
    "How do I stop procrastinating?",
    "What are some effective ways to deal with anxiety?",
    "How do I improve my focus?",
    "What are some ways to boost creativity?",
    "How do I develop a growth mindset?",
    "What is the power of positive thinking?",
    "How do I stay disciplined?",
    "What are some common public speaking tips?",
    "How do I improve my critical thinking skills?",
    "If you could have any superpower, what would it be?",
    "What is the funniest prank ever played?",
    "Why do dogs chase their tails?",
    "What is the weirdest food combination people enjoy?",
    "What is the strangest law in the world?",
    "Why do we dream?",
    "How do chameleons change color?",
    "What are some weird facts about space?",
    "What are the most mysterious places on Earth?",
    "If you could live in any time period, which one would you choose?",
    "What is the history of the internet?",
    "How do search engines work?",
    "What is the metaverse?",
    "What is the dark web?",
    "How do VPNs protect privacy?",
    "What is the future of artificial intelligence?",
    "What is blockchain technology?",
    "How does facial recognition work?",
    "What are the risks of using social media?",
    "What is the difference between AR and VR?",
]

dataset_size = 500
dataset = []

for _ in range(dataset_size // 2):
    dataset.append((random.choice(math_questions), 1))
    dataset.append((random.choice(non_math_questions), 0))

df = pd.DataFrame(dataset, columns=["text", "is_math"])

train_texts, test_texts, train_labels, test_labels = train_test_split(df["text"], df["is_math"], test_size=0.2, random_state=42)

tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")

train_encodings = tokenizer(list(train_texts), truncation=True, padding=True, max_length=128)
test_encodings = tokenizer(list(test_texts), truncation=True, padding=True, max_length=128)

class MathDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

train_dataset = MathDataset(train_encodings, list(train_labels))
test_dataset = MathDataset(test_encodings, list(test_labels))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=2)
model.to(device)

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    logging_dir="./logs",
    logging_steps=10,
    load_best_model_at_end=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=DataCollatorWithPadding(tokenizer=tokenizer),
)

trainer.train()

model.save_pretrained("math_classifier_distilbert")
tokenizer.save_pretrained("math_classifier_distilbert")
torch.save(model.state_dict(), "math_classifier_distilbert/pytorch_model.bin")

print("Model training complete!")